[package]
name = "bevy_request"
version = "0.1.0-alpha.1"
edition = "2024"
description = "A HTTP client library for bevy"
documentation = "https://docs.rs/bevy-request"
homepage = "https://github.com/xbwwj/bevy-request"
license = "MIT OR Apache-2.0"

[dependencies]
async-compat = "0.2.5"
bevy = { version = "0.18.0", default-features = false, features = [
  "bevy_log",
  "std"
] }
crossbeam-channel = "0.5.15"
reqwest = { version = "0.13.1", features = ["json"] }
serde = "1.0.228"

[features]
